[package]
name = "www-redirector"
version = "0.2.0"
edition = "2021"

[dependencies]
hyper = { version = "1.1", features = ["full"] }
tokio = { version = "1.36", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
bytes = "1.5"
